# Generated by Django 4.1.3 on 2023-05-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_football', '0003_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(max_length=50),
        ),
    ]
