# Generated by Django 4.1.3 on 2023-05-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_football', '0004_alter_player_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
